// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbxvhureokfuqldlildk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpieHZodXJlb2tmdXFsZGxpbGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjM2MDIsImV4cCI6MjA2NTk5OTYwMn0.a6nu47X_bSlGvSHLEzm-zwY0dIOeOuEBKbXiXhUtqME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);