// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqsvmuelbnsfqwxoauem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxc3ZtdWVsYm5zZnF3eG9hdWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTgwNTksImV4cCI6MjA2MzU5NDA1OX0.iAfqbjNGGtz98CPmtpkuzZenZuXlN-Io8DkbJ3ikrHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);